### ISSUE TITLE
ERROR when building, --> include <ft2build.h>

### ISSUE THREAD

**Issue by Jopro1990** [reezliabi/CS2-External-Usermode#1]
There is no such file in this project?!
![Screenshot 2024-01-12 164623](https://github.com/reezliabi/CS2-External-Usermode/assets/129279032/70e45bf0-b424-4c75-ae42-3415edab91ce)

**Comment by reezliabi** [comment]
there is.

go to:
fhook/thirdparty/freetype/

unpack the zip folder and correct your includes and libs in project settings

**Comment by Jopro1990** [comment]
Nah i did unzip the include&lib.zip , but it still does not build correctly even though I did add all of them to the project?!
