### ISSUE TITLE
Error in programm

### ISSUE THREAD

**Issue by Jopro1990** [reezliabi/CS2-External-Usermode#2]
why am i getting this error? i built with default settings, like u said I should!
![Screenshot 2024-01-13 173004](https://github.com/reezliabi/CS2-External-Usermode/assets/129279032/fee493d9-da2a-4b30-8d1d-1aa2442bf6a8)

**Comment by larcencial** [comment]
Same for me too and aimbot not working

**Comment by Jopro1990** [comment]
I dont get a gui even though it said it created one @larcencial

**Comment by reezliabi** [comment]
Add me on discord to get the compiled version:
necrumbaby_65817


You dont even need to change something in the Source, its ready to use.
This is basic C++, you need to set libs and include linkers:

1)extract fhook/thirdparty/freetype/include&lib.zip in the same folder
2) go to project-> properties
3) c/c++ --> General and add Include file which was in include&lib/freetype/include(add this path in Additional Include Directories)
4) Now go to linker (below C/C++)-> general
5) add objs(include&lib/freetype/objs) in to Additional Library Directories

**Comment by Jopro1990** [comment]
alright added you, ty @reezliabi

**Comment by yangyuan-zhen** [comment]
I have the same problem as you, have you solved it?

**Comment by larcencial** [comment]
@AmandaloveYang add libs to directx sdk (normal and debug both of them)
