### ISSUE TITLE
.

### ISSUE THREAD

**Issue by T1GxR** [reezliabi/CS2-External-Usermode#5]

**Comment by snkfranco** [comment]
Source is not working anymore. Needs update. Loved that ch3at
:(

**Comment by reezliabi** [comment]
It takes 2 minutes to update this Cheat, you need to update the Offsets and Signatures in the Source Code, compile new build, and youre done ✅

**Comment by T1GxR** [comment]
> It takes 2 minutes to update this Cheat, you need to update the Offsets and Signatures in the Source Code, compile new build, and youre done ✅

i updated all offsets but idk where to find those signatures, can you give me some tips on where do i find them? i looked in the game sdk and i only found like 6 signatures and none of them are the same as the one needed...

**Comment by T1GxR** [comment]
and i also fixed all the errors, including the one from this issue!

**Comment by T1GxR** [comment]
> It takes 2 minutes to update this Cheat, you need to update the Offsets and Signatures in the Source Code, compile new build, and youre done ✅

where do i find all signatures easier? i only found like 6 main signatures and none of them matches the ones needed. I don't actually have time to reverse the game...
